### ISSUE TITLE
스켈레톤 작성

### ISSUE THREAD

**Issue by celestine147** [celestine147/calculator#1]
- main() 함수

**Comment by celestine147** [comment]
사칙연산을 담당하는 각각의 함수를 작성하는 것이 좋겠습니다. 
예를들면 'add' 'sub' 등등

**Comment by dykng007** [comment]
함수 작성전에 gui를 먼저 구성하고 작성을 시작 하는 것이 좋겠습니다.

**Comment by celestine147** [comment]
fixed #1 comfirm complete!
